# Generated by Django 4.2.2 on 2023-06-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_product_users_wishlist"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Required", max_length=255, verbose_name="title"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Not Required", verbose_name="description"
                    ),
                ),
                ("slug", models.SlugField(max_length=255)),
                (
                    "regular_price",
                    models.DecimalField(
                        decimal_places=2,
                        error_messages={
                            "name": {
                                "max_length": "The price must be between 0 and 9999.99."
                            }
                        },
                        help_text="Maximum 9999.99",
                        max_digits=6,
                        verbose_name="Regular price",
                    ),
                ),
                (
                    "discount_price",
                    models.DecimalField(
                        decimal_places=2,
                        error_messages={
                            "name": {
                                "max_length": "The price must be between 0 and 9999.99."
                            }
                        },
                        help_text="Maximum 9999.99",
                        max_digits=6,
                        verbose_name="Discount price",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Change ticket visibility",
                        verbose_name="Ticket visibility",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
            ],
            options={
                "verbose_name": "Ticket",
                "verbose_name_plural": "Tickets",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="TicketImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="images/default.png",
                        help_text="Upload a ticket image",
                        upload_to="images/",
                        verbose_name="image",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Please add alturnative text",
                        max_length=255,
                        null=True,
                        verbose_name="Alturnative text",
                    ),
                ),
                ("is_feature", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Ticket Image",
                "verbose_name_plural": "Ticket Images",
            },
        ),
        migrations.CreateModel(
            name="TicketSpecificationValue",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Ticket specification value (maximum of 255 words",
                        max_length=255,
                        verbose_name="value",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket Specification Value",
                "verbose_name_plural": "Ticket Specification Values",
            },
        ),
        migrations.CreateModel(
            name="TicketType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Required",
                        max_length=255,
                        unique=True,
                        verbose_name="Ticket Name",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Ticket Type",
                "verbose_name_plural": "Ticket Types",
            },
        ),
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.RemoveField(
            model_name="product",
            name="product_type",
        ),
        migrations.RemoveField(
            model_name="product",
            name="users_wishlist",
        ),
        migrations.RemoveField(
            model_name="productimage",
            name="product",
        ),
        migrations.RemoveField(
            model_name="productspecificationvalue",
            name="product",
        ),
        migrations.RemoveField(
            model_name="productspecificationvalue",
            name="specification",
        ),
        migrations.AlterModelOptions(
            name="ticketspecification",
            options={
                "verbose_name": "Ticket Specification",
                "verbose_name_plural": "Ticket Specifications",
            },
        ),
        migrations.RenameModel(
            old_name="ProductSpecification",
            new_name="TicketSpecification",
        ),
    ]
