# Generated by Django 4.2.2 on 2023-06-26 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_orderitem_product"),
        ("store", "0003_ticket_ticketimage_ticketspecificationvalue_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.DeleteModel(
            name="ProductImage",
        ),
        migrations.DeleteModel(
            name="ProductSpecificationValue",
        ),
        migrations.DeleteModel(
            name="ProductType",
        ),
        migrations.AddField(
            model_name="ticketspecificationvalue",
            name="specification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="store.ticketspecification",
            ),
        ),
        migrations.AddField(
            model_name="ticketspecificationvalue",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="store.ticket"
            ),
        ),
        migrations.AddField(
            model_name="ticketimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ticket_image",
                to="store.ticket",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="store.category"
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="ticket_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="store.tickettype"
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="users_wishlist",
            field=models.ManyToManyField(
                blank=True, related_name="user_wishlist", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="ticketspecification",
            name="product_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="store.tickettype"
            ),
        ),
    ]
