# Generated by Django 4.2.2 on 2023-06-26 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="address1",
        ),
        migrations.RemoveField(
            model_name="order",
            name="address2",
        ),
        migrations.RemoveField(
            model_name="order",
            name="country_code",
        ),
        migrations.RemoveField(
            model_name="order",
            name="postal_code",
        ),
    ]
