# Generated by Django 4.2.2 on 2023-06-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_auto_20210322_1634"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
