# Generated by Django 4.2.2 on 2023-06-26 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_ticket_ticketimage_ticketspecificationvalue_and_more"),
        ("orders", "0003_alter_orderitem_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items",
                to="store.ticket",
            ),
        ),
    ]
